name: augmentation-agent-topic
channels:
  - conda-forge
  - pytorch
  - huggingface
dependencies:
  - python=3.10
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scikit-learn>=1.1.0
  - nltk>=3.7
  - plotly>=5.10.0
  - jupyter>=1.0.0
  - pytest>=7.0.0
  - pip>=22.0.0
  - pip:
    - bertopic>=0.15.0
    - openai>=1.0.0
    - langchain>=0.1.0
    - tiktoken>=0.5.0
    - transformers>=4.30.0
    - torch>=2.0.0
    - sentence-transformers>=2.2.0
    - umap-learn>=0.5.3
    - hdbscan>=0.8.29
    - python-dotenv>=1.0.0
    - tqdm>=4.64.0
    - colorama>=0.4.6