name: augmentation-agent-topic
channels:
  - conda-forge
  - pytorch
  - huggingface
  - nvidia  # For CUDA support
dependencies:
  # Python and core packages
  - python=3.10
  - pip>=22.0.0

  # Data processing (conda-forge preferred)
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scikit-learn>=1.1.0
  - scipy>=1.9.0

  # ML/DL frameworks (from appropriate channels)
  - pytorch>=2.0.0
  - pytorch-cuda=11.8  # Optional: for CUDA support
  - cudatoolkit=11.8   # Optional: for CUDA support

  # Utilities (conda-forge)
  - tqdm>=4.64.0
  - colorama>=0.4.6
  - python-dotenv>=1.0.0
  - click>=8.0.0
  - pathlib2
  - requests>=2.28.0

  # Development tools (conda-forge)
  - jupyter>=1.0.0
  - pytest>=7.0.0
  - black
  - flake8
  - isort

  # Visualization (conda-forge)
  - plotly>=5.10.0
  - matplotlib>=3.5.0
  - seaborn>=0.11.0

  # NLP preprocessing (conda-forge when available)
  - nltk>=3.7

  # Packages that perform better via pip
  - pip:
    # Topic modeling and embeddings
    - bertopic>=0.15.0
    - sentence-transformers>=2.2.0
    - transformers>=4.30.0

    # OpenAI and LLM packages
    - openai>=1.0.0
    - langchain>=0.1.0
    - tiktoken>=0.5.0

    # Clustering and dimensionality reduction
    - umap-learn>=0.5.3
    - hdbscan>=0.8.29

    # Additional utilities
    - python-dateutil>=2.8.0